# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
logo:
  src: skoolink.png
  show_in_header: true

app_title: Master Data Skoolink

backend:
  name: github
  repo: inalix/inalix.github.io
  branch: main
  base_url: https://sve-auth.styawan.workers.dev

media_folder: static/uploads
public_folder: /media

collections:
  - name: team
    label: Team 
    identifier_field: name
    path: '{{slug}}/index' 
    folder: /data-team
    public_folder: .
    media_folder: .
    description: Apa ya kira-kira
    summary: "{{name}} lahir {{birthday}}"
    editor:
      preview: false
    fields:
      - name: name
        widget: string
      - name: birthday
        widget: datetime
      - name: division
        widget: string
      - name: photo
        widget: image

  - name: administrative_area
    label: Administrative Area
    label_singular: Administrative Area
    folder: /wilayah
    identifier_field: data.code
    summary: "{{slug}}/L{{meta.administrative_area_level}} at {{meta.updated_at}}"
    format: json
    editor:
      preview: false
    reorder:
      key: weight
    fields:
      - label: Meta
        name: meta
        widget: object
        fields:
          - label: Level
            name: administrative_area_level
            widget: string
          - label: Urutan
            name: updated_at
            widget: datetime
      - label: Data
        name: data
        widget: list
        summary: "summary {{code}} {{name}}"
        collapsed: true
        fields:
          - label: Code
            name: code
            widget: string
            maxlength: 5
          - label: Name
            name: name
            widget: string

  - name: provinces
    label: Province
    folder: /provinces
    identifier_field: code
    summary: "{{slug}} {{name}}"
    format: yaml
    editor:
      preview: false
    reorder:
      key: weight
    fields:
      - { label: Level, name: administrative_area_level, value: 1, widget: hidden }
      - { label: Urutan, name: updated_at, widget: hidden, default: "{{datetime}}" }
      - label: Code
        name: code
        widget: string
        maxlength: 2
      - label: Name
        name: name
        widget: string
      - name: map
        widget: map
        type: Point
        center: [106.827168,-6.1754049] 
        zoom: 11


  - name: districts
    label: District
    folder: /districts
    identifier_field: code
    summary: "{{slug}} {{name}}"
    format: json
    view_groups:
      - field: province
        label: Province
    editor:
      preview: false
    reorder:
      key: weight
    fields:
      - { label: Level, name: administrative_area_level, value: 2, widget: hidden }
      - { label: Urutan, name: updated_at, widget: hidden, default: "{{datetime}}" }
      - label: Province
        name: province
        widget: relation
        collection: provinces
        display_fields:
        - slug
        - name
      - label: Code
        name: code
        widget: string
        maxlength: 5
      - label: Name
        name: name
        widget: string
