name: Deploy Admin to Public

on:
  push:
    branches:
      - admin


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.6
        with:
          folder: admin
          target-folder: admin
          branch: public
          force: false # dari banyak sumber
